# for loop syntax:
for <var> in <iterable> :   
    ...............
    ...............
    ...............


# while loop syntax:
while <stmt/condition> :    
    ...............
    ...............
    ...............